---
abstract: 'Perl interface to the gd2 graphics library'
author:
  - 'Lincoln Stein <lincoln.stein@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::Fork: '0.02'
  Test::More: '0.88'
configure_requires:
  ExtUtils::Constant: '0.22'
  ExtUtils::PkgConfig: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.38, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: GD
no_index:
  directory:
    - t
    - inc
recommends:
  Class::XSAccessor: '0'
  ExtUtils::Constant: '0.23'
  List::MoreUtils: '0'
  Pod::Spell::CommonMistakes: '0'
  Test::Kwalitee: '0'
  Test::More: '0.88'
  Test::Pod: '1.00'
  Text::CSV_XS: '0'
requires:
  Math::Trig: '0'
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/lstein/Perl-GD
version: '2.73'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
